name: build_env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy>=1.26
  - torch>=2.0,<2.3
  - scanpy>=1.10,<1.11
  - anndata>=0.10
  - matplotlib-base>=3.6,<3.9
  - pillow>=8.0
  - conda-build
  - anaconda-client
