{% set version = environ.get('GIT_TAG_NAME', '0.0.0') %}

package:
  name: scregulate
  version: "{{ version }}"

source:
  path: ..

build:
  noarch: python
  script: python -m pip install .
  number: 0

requirements:
  host:
    - python >=3.10,<3.11
    - pip
  run:
    - python >=3.10,<3.11
    - numpy >=1.26
    - pytorch >=2.0,<2.3
    - scanpy >=1.10,<1.11
    - anndata >=0.10
    - matplotlib-base >=3.6,<3.9
    - pillow >=8.0

test:
  imports:
    - scregulate
  commands:
    - pip check
  requires:
    - pip
  source_files:
    - setup.py
  channels:
    - conda-forge
    - pytorch

about:
  home: https://github.com/YDaiLab/scRegulate
  dev_url: https://github.com/YDaiLab/scRegulate
  license: MIT
  license_file: LICENSE
  summary: Python Toolkit for Transcription Factor Activity Inference and Clustering of scRNA-seq Data
  description: |
    scRegulate is a Python toolkit designed for inferring transcription factor activity
    and clustering single-cell RNA-seq data using variational inference with biological priors.
    It is built on PyTorch and Scanpy, and supports CUDA acceleration for high-performance inference.
