name: Publish Conda Package

on:
  release:
    types: [published]

jobs:
  build-and-upload-conda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3.0.4
        with:
          auto-update-conda: true
          python-version: 3.9
          activate-environment: build_env

      - name: Install conda-build and anaconda-client
        shell: bash -l {0}
        run: |
          conda install -n build_env -c conda-forge conda-build anaconda-client -y

      - name: Build conda package
        shell: bash -l {0}
        run: |
          conda activate build_env
          conda build conda.recipe --output-folder dist

      - name: Upload to Anaconda
        shell: bash -l {0}
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          conda activate build_env
          for file in dist/*/*.tar.bz2; do
            anaconda -t "$ANACONDA_TOKEN" upload "$file" --force
          done
